### ISSUE TITLE
No link to the website on the github

### ISSUE THREAD

**Issue by Ultra-bob** [EurekaHackathon/EurekaHacks2024#5]
## APMC GIthub
![image](https://github.com/EurekaHackathon/EurekaHacks2024/assets/66791664/6cb7eaae-40ac-4fcf-a077-0d22a675fdff)
## Eureka Github
![image](https://github.com/EurekaHackathon/EurekaHacks2024/assets/66791664/3e3a2573-4606-4188-a0cb-b7eaf52eea6f)

**Comment by Leg3ndary** [comment]
These are 2 separate organizations and GitHub is not the primary way people find this website, the only reason it's public as of now is that it needs to make use of Netlify's free tier... In any case I suppose it doesn't really matter so added
