### ISSUE TITLE
The sponsors aren't aligned and/or dont have a transparent background

### ISSUE THREAD

**Issue by Ultra-bob** [EurekaHackathon/EurekaHacks2024#6]
(on arc browser which is chromium based iirc)

![image](https://github.com/EurekaHackathon/EurekaHacks2024/assets/66791664/0aa9dcf6-6871-4d24-afbb-b7b60c0f54dc)

**Comment by Leg3ndary** [comment]
They are aligned in the center though? We purposefully added a white background, the varying sizes are to represent tiers as you can probably infer from the CSS. It's only temporary until we start adding more sponsors.
